
package Consultas;

import Entidad.dtos.ProductDto;
import java.awt.Dimension;
import java.awt.Image;
import java.text.SimpleDateFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import statics.Design;
import statics.ImageLoader;
import statics.Paths;
import statics.ScreenUses;

public class FrmProductInformation extends javax.swing.JInternalFrame {

    private ProductDto productDto;
    
    /**
     * Creates new form FrmProductInformation
     */
    public FrmProductInformation(ProductDto productDto) {
        this.productDto = productDto;
        initComponents();
        setVisible(true);
        lblImage.setSize(310, 310);
        loadData();
        this.getContentPane().setBackground(Design.COLOR_PRIMARY_DARK);
        this.setLocation((ScreenUses.getHorizontal() / 2) - (getWidth() / 2), (ScreenUses.getVertical() / 2) - (getHeight() / 2));
    }
    
    public void loadData(){
        lblId.setText(String.valueOf(productDto.getId()));
        lblBarcode.setText(productDto.getCode());
        lblName.setText(productDto.getName());
        lblDescription.setText(productDto.getDescription());
        lblStock.setText(productDto.getStock());
        lblMinimunStock.setText(productDto.getMinStock());
        lblCost.setText(productDto.getCoste());
        lblGirlCost.setText(productDto.getGirlCost());
        lblSalePrice.setText(productDto.getPrice());
        lblUtility.setText(productDto.getUtility());
        lblState.setText(productDto.getState());
        lblCategory.setText(productDto.getCategory()); // contiene el nombre de la categoría
        if(productDto.getImageIcon() != null){
            try {
                Icon icon = new ImageIcon(productDto.getImageIcon().getImage().getScaledInstance(
                        lblImage.getWidth(),
                        lblImage.getHeight(),
                        Image.SCALE_FAST)
                );
                lblImage.setIcon(icon);
            } catch (Exception e) {
                ImageLoader.setImage(lblImage, Paths.DEFAULT_PRODUCT_IMAGE);
            }
        }else{
            ImageLoader.setImage(lblImage, Paths.DEFAULT_PRODUCT_IMAGE_WHITE);
        }
        if(productDto.getExpiration() != null){
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            lblExpirationDate.setText(formatter.format(productDto.getExpiration()));
        }else{
            lblExpirationDate.setText("Sin definir");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblExpirationDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblBarcode = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMinimunStock = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSalePrice = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblUtility = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblGirlCost = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Producto");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(700, 670));
        setMinimumSize(new java.awt.Dimension(355, 355));
        setPreferredSize(new java.awt.Dimension(700, 355));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setForeground(new java.awt.Color(204, 204, 255));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(335, 310));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExpirationDate.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblExpirationDate.setForeground(new java.awt.Color(255, 255, 255));
        lblExpirationDate.setText("empty");
        jPanel3.add(lblExpirationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 269, 162, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("FECHA DE VENCIMINTO: ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 269, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("ID: ");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 13, -1, -1));

        lblId.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("empty");
        jPanel3.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 13, 260, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("CÓDIGO DE BARRAS:  ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 34, -1, -1));

        lblBarcode.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblBarcode.setForeground(new java.awt.Color(255, 255, 255));
        lblBarcode.setText("empy");
        jPanel3.add(lblBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 34, 147, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("NOMBRE: ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 56, -1, -1));

        lblName.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("empy");
        jPanel3.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 56, 211, -1));

        lblDescription.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblDescription.setText("Empty");
        jPanel3.add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 102, 300, 29));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("DESCRIPCIÓN: ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 83, 103, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("STOCK: ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 137, -1, -1));

        lblStock.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblStock.setForeground(new java.awt.Color(255, 255, 255));
        lblStock.setText("empty");
        jPanel3.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 137, 70, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("STOCK MÍN: ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        lblMinimunStock.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblMinimunStock.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimunStock.setText("empty");
        jPanel3.add(lblMinimunStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 70, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("COSTO PR.: ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 170, -1, -1));

        lblCost.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblCost.setForeground(new java.awt.Color(255, 255, 255));
        lblCost.setText("empty");
        jPanel3.add(lblCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 55, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("PRECIO DE VENTA: ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 203, -1, -1));

        lblSalePrice.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblSalePrice.setForeground(new java.awt.Color(255, 255, 255));
        lblSalePrice.setText("empty");
        jPanel3.add(lblSalePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 203, 59, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("UTILIDAD: ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 203, -1, -1));

        lblUtility.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblUtility.setForeground(new java.awt.Color(255, 255, 255));
        lblUtility.setText("empty");
        jPanel3.add(lblUtility, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 203, 54, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("ESTADO: ");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 236, -1, -1));

        lblState.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblState.setForeground(new java.awt.Color(255, 255, 255));
        lblState.setText("empty");
        jPanel3.add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 236, 80, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("CATEGORÍA: ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 236, 100, -1));

        lblCategory.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblCategory.setText("empty");
        jPanel3.add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 236, 90, -1));

        lblGirlCost.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblGirlCost.setForeground(new java.awt.Color(255, 255, 255));
        lblGirlCost.setText("empty");
        jPanel3.add(lblGirlCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 80, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("COSTO CH.: ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        getContentPane().add(jPanel3);

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(335, 310));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Box.png"))); // NOI18N
        lblImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblImage.setPreferredSize(new java.awt.Dimension(300, 300));
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });
        jPanel5.add(lblImage);

        getContentPane().add(jPanel5);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        if(getSize().getWidth() == 700)
            setSize(new Dimension(355, 670));
        else
            setSize(new Dimension(700, 355));
    }//GEN-LAST:event_lblImageMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblBarcode;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblGirlCost;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMinimunStock;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSalePrice;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblUtility;
    // End of variables declaration//GEN-END:variables
}
